CREATE TABLE `tournaments` (
    `id` int NOT NULL AUTO_INCREMENT,
    `type` ENUM('dab', 'handicap') NOT NULL,
    `creator` int NOT NULL,
    `name` varchar(100) NOT NULL,
    `description` varchar(2048) DEFAULT NULL,
    `challongeLink` varchar(2048) DEFAULT NULL,
    `logoLink` varchar(2048) DEFAULT NULL,
    `startDate` date NOT NULL,
    `checkinDate` date NOT NULL,
    PRIMARY KEY (`id`)
);

CREATE TABLE `tournament_entries` (
    `id` int NOT NULL AUTO_INCREMENT,
    `tournamentID` int NOT NULL,
    `configId` int NOT NULL,
    `isLocked` boolean NOT NULL DEFAULT false,
    PRIMARY KEY (`id`)
);

CREATE TABLE `dab_configs` (
    `id` int NOT NULL AUTO_INCREMENT,
    `entryId` int NOT NULL,
    `member1` int NOT NULL,
    `member1Race` ENUM('zerg','terran','protoss'),
    `member1NumBans` int NOT NULL,
    `member1Ban1` varchar(30) DEFAULT NULL,
    `member1Ban2` varchar(30) DEFAULT NULL,
    `member1Ban3` varchar(30) DEFAULT NULL,
    `member1Ban4` varchar(30) DEFAULT NULL,
    `member1Ban5` varchar(30) DEFAULT NULL,
    `member1Ban6` varchar(30) DEFAULT NULL,
    `member1Confirmed` boolean NOT NULL DEFAULT false,
    `member2` int NOT NULL,
    `member2Race` ENUM('zerg','terran','protoss'),
    `member2NumBans` int NOT NULL,
    `member2Ban1` varchar(30) DEFAULT NULL,
    `member2Ban2` varchar(30) DEFAULT NULL,
    `member2Ban3` varchar(30) DEFAULT NULL,
    `member2Ban4` varchar(30) DEFAULT NULL,
    `member2Ban5` varchar(30) DEFAULT NULL,
    `member2Ban6` varchar(30) DEFAULT NULL,
    `member2Confirmed` boolean NOT NULL DEFAULT false,
    PRIMARY KEY (`id`)
);

CREATE TABLE `units` (
    `name` varchar(30) NOT NULL,
    `race` ENUM('zerg','terran','protoss'),
    `dabCanBan` boolean NOT NULL,
    PRIMARY KEY (`name`)
);

INSERT INTO `units` (`name`, `race`, `dabCanBan`) VALUES
    ('SCV', 'terran', false),
    ('MULE', 'terran', false),
    ('Marine', 'terran', true),
    ('Marauder', 'terran', true),
    ('Reaper', 'terran', true),
    ('Ghost', 'terran', true),
    ('Hellion', 'terran', true),
    ('Hellbat', 'terran', true),
    ('Siege Tank', 'terran', true),
    ('Cyclone', 'terran', true),
    ('Widow Mine', 'terran', true),
    ('Thor', 'terran', true),
    ('Viking', 'terran', true),
    ('Medivac', 'terran', true),
    ('Liberator', 'terran', true),
    ('Raven', 'terran', true),
    ('Banshee', 'terran', true),
    ('Battlecruiser', 'terran', true),

    ('Probe', 'protoss', false),
    ('Zealot', 'protoss', true),
    ('Stalker', 'protoss', true),
    ('Sentry', 'protoss', true),
    ('Adept', 'protoss', true),
    ('High Templar', 'protoss', true),
    ('Dark Templar', 'protoss', true),
    ('Immortal', 'protoss', true),
    ('Collosus', 'protoss', true),
    ('Disruptor', 'protoss', true),
    ('Observer', 'protoss', true),
    ('Warp Prism', 'protoss', true),
    ('Phoenix', 'protoss', true),
    ('Void Ray', 'protoss', true),
    ('Oracle', 'protoss', true),
    ('Carrier', 'protoss', true),
    ('Tempest', 'protoss', true),
    ('Mothership', 'protoss', true),

    ('Drone', 'zerg', false),
    ('Queen', 'zerg', false),
    ('Zergling', 'zerg', true),
    ('Baneling', 'zerg', true),
    ('Roach', 'zerg', true),
    ('Ravager', 'zerg', true),
    ('Hydralisk', 'zerg', true),
    ('Lurker', 'zerg', true),
    ('Infestor', 'zerg', true),
    ('Swarm Host', 'zerg', true),
    ('Ultralisk', 'zerg', true),
    ('Overseer', 'zerg', false),
    ('Dropperlord', 'zerg', true),
    ('Mutalisk', 'zerg', true),
    ('Corruptor', 'zerg', true),
    ('Viper', 'zerg', true),
    ('Brood Lord', 'zerg', true)
